services:
  - type: web
    name: fanorona-relay-express
    runtime: node
    plan: free
    rootDir: backend/relay-express
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
